### ISSUE TITLE
Don't rely on Sid for any policies

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-s3-gw#1023]
## Current Behavior
#1018 has introduced some logic dependent on `BucketEnableACL` Sid, but it's absolutely incorrect. 

## Expected Behavior
Sid is informational and can be named in any way, what matters is Action/Resource/Effect.
https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_sid.html

## Possible Solution
Do not check for Sid, check contents only.

## Context
#1016, https://github.com/nspcc-dev/neofs-testcases/pull/894

**Comment by evgeniiz321** [comment]
Why are we using policies to enable/disable ACLs? I found this command - https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutBucketOwnershipControls.html
To enable ACLs (both on a bucket and objects):

```
➜  ~ aws s3api put-object-acl --bucket s3gwacldis --key ez_test_file1 --acl public-read

An error occurred (AccessControlListNotSupported) when calling the PutObjectAcl operation: The bucket does not allow ACLs
➜  ~ aws s3api put-bucket-ownership-controls --bucket s3gwacldis --ownership-controls '{
    "Rules": [
        {
            "ObjectOwnership": "BucketOwnerPreferred"
        }
    ]
}'

➜  ~ aws s3api put-object-acl --bucket s3gwacldis --key ez_test_file1 --acl public-read
```
And to disable:
```
➜  ~ aws s3api put-bucket-ownership-controls --bucket s3gwacldis --ownership-controls '{
    "Rules": [
        {
            "ObjectOwnership": "BucketOwnerEnforced"
        }
    ]
}'

➜  ~ aws s3api put-bucket-acl --bucket s3gwacldis --acl public-read

An error occurred (AccessControlListNotSupported) when calling the PutBucketAcl operation: The bucket does not allow ACLs
```

**Comment by evgeniiz321** [comment]
As for policies - we do not handle them correctly, e.g. this policy is not accepted by amazon s3:
```
{
"Statement": [
    {
        "Sid": "BucketEnableACL",
        "Effect": "Allow",
        "Action": ["s3:PutObject"],
        "Resource": ["*"]
    }
]
}
```
Amazon requires Principal to be set and Resource should have a different format. This is the right policy that is accepted by amazon:
```
{
    "Statement": [
        {
            "Sid": "BucketEnableACL",
            "Principal": "*",
            "Effect": "Allow",
            "Action": ["s3:PutObject"],
            "Resource": ["arn:aws:s3:::s3gwacldis/*"]
        }
    ]
}
```
