### ISSUE TITLE
Check Content-MD5 header

### ISSUE THREAD

**Issue by KirillovDenis** [nspcc-dev/neofs-s3-gw#188]
Sometimes `Content-MD5` header is provided with `PutObject` (https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObject.html) request and we have to handle it. However we should compute not MD-5 but sha256? because we already use it as `ETag`.

**Comment by realloc** [comment]
Implementing the `Content-MD5` as it's described in the AWS spec can be done either by introducing intermediate content buffering or cancelling the "bad" request when it's already streaming the content to NeoFS Storage node. Both ways seem to be suboptimal.

For now, we won't support this. Later, if there is a demand for this, we can reconsider the decision.

**Comment by realloc** [comment]
As written in [UploadPart](https://docs.aws.amazon.com/AmazonS3/latest/API/API_UploadPart.html) description, PUT request could use the `x-amz-content-sha256` header as a checksum instead of `Content-MD5` with the same behaviour.
