### ISSUE TITLE
Support browser-based uploads using POST

### ISSUE THREAD

**Issue by KirillovDenis** [nspcc-dev/neofs-s3-gw#190]
I suppose it's quite useful feature https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-UsingHTTPPOST.html and we should implement it. But there may be problems with acl (#49) (that is provided in policy)

**Comment by realloc** [comment]
Let's discuss  moving this feature to http gateway.

**Comment by KirillovDenis** [comment]
Moving? Not duplicate?

**Comment by realloc** [comment]
That's what I want to discuss =) It looks like this could be handled by http-gw better, as it already has working upload with streaming support. It only lacks the signature check part that should use the authbox or just check the signature against the container owner public key.

**Comment by realloc** [comment]
Maybe we should consider the following plan:
- Port s3-gw to fasthttp
- Re-implement streaming upload/download
- Add POST upload with in-place ACL translation/check
