### ISSUE TITLE
Support object locking

### ISSUE THREAD

**Issue by KirillovDenis** [nspcc-dev/neofs-s3-gw#195]
Should we support [object locking](https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-lock.html)?

There are some problems:
* Where will the flag (that enable this functionality when bucket creating) be stored?
* Where will the object lock configuration be stored?

The similar problems must be solved in #122 so it issue should be done later anyway.

**Comment by realloc** [comment]
As I understood, Object locking can be considered enabled for all buckets with versioning?

If so, then we could add one more list for hold/retention and alter the DELETE logic to check that.

**Comment by KirillovDenis** [comment]
We need to update sdk up to version that conains https://github.com/nspcc-dev/neofs-sdk-go/pull/140.  So this issue is blocked by https://github.com/nspcc-dev/neofs-s3-gw/pull/346 that made s3-gw use to sdk v1.0.0-rc.1 in general
