### ISSUE TITLE
Tagging support

### ISSUE THREAD

**Issue by KirillovDenis** [nspcc-dev/neofs-s3-gw#196]
We should implement [tagging support](https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-tagging.html):
* [PutObjectTagging](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObjectTagging.html)
* [GetObjectTagging](https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetObjectTagging.html)
* [DeleteObjectTagging](https://docs.aws.amazon.com/AmazonS3/latest/API/API_DeleteObjectTagging.html)

I suppose we have to create new objects for every tag changing. So this issue is blocked by #122

**Comment by KirillovDenis** [comment]
We can also consider:
* [GetBucketTagging](https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetBucketTagging.html)
* [PutBucketTagging](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutBucketTagging.html)
* [DeleteBucketTagging](https://docs.aws.amazon.com/AmazonS3/latest/API/API_DeleteBucketTagging.html)

**Comment by KirillovDenis** [comment]
We can create a new object and store a set of tags in its attribute. In addition, we must use the special attribute `S3-Versions-ignore: true` to prevent versioning of these system objects. Also, we should name this object something like `.tagset.object-name.object-identifier`

**Comment by realloc** [comment]
That should not be a key name, to prevent listing. We should use some other attribute.

**Comment by KirillovDenis** [comment]
> That should not be a key name, to prevent listing. We should use some other attribute.

Should the settings object `.s3-gw-settings` also have the same attribute (e.g. `S3-System-name`) instead of `FileName`?

**Comment by realloc** [comment]
> Should the settings object `.s3-gw-settings` also have the same attribute (e.g. `S3-System-name`) instead of `FileName`?

Yes
