### ISSUE TITLE
Update Authmate section in README

### ISSUE THREAD

**Issue by KirillovDenis** [nspcc-dev/neofs-s3-gw#210]
Sometimes people try to put some objects in bucket/container (which was created by `authmate --issue-secret`) as a result, this operation fails because such container doesn't have public basic ACL.
We should update docs or revise basic and extended ACL of container that stores bearer tokens.

**Comment by realloc** [comment]
Maybe we also should consider breaking down the `README.md` into a set of smaller files in `doc/` directory.
