### ISSUE TITLE
Object ACL versioning

### ISSUE THREAD

**Issue by KirillovDenis** [nspcc-dev/neofs-s3-gw#213]
[GetObjectAcl](https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetObjectAcl.html) and [PutObjectAcl](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObjectAcl.html) support versioning (acl can be applied to specific version). So current (#176) applying eacl rules by object name looks a little bit odd (if we want to support such acl versioning).

I see the following solutions:
* Use `object id` (s3 version) in eacl rules (need some changes in [neofs-api-go](https://github.com/nspcc-dev/neofs-api-go)). New method to add `object id` filter can be introduced (similar to `AddObjectContainerIDFilter`). The con is we still have limitation for eacl size https://github.com/nspcc-dev/neofs-node/issues/731
* Perhaps we can use solution https://github.com/nspcc-dev/neofs-api/issues/163

**Comment by realloc** [comment]
Let's go with the first option. We assume the S3 protocol gateway works with normal size eACL capable SideChain deployment.
