### ISSUE TITLE
Add a way to map bucket name and cid conveniently.

### ISSUE THREAD

**Issue by masterSplinter01** [nspcc-dev/neofs-s3-gw#220]
A container has two "names" -- bucket name in aws and ID in NeoFS. It's inconvenient to map nice name into cid via neofs-cli/logs/debugger etc. 

Maybe we can add container ID as an attribute of a bucket and print it via s3api?

**Comment by KirillovDenis** [comment]
We can set `X-Container-Id` header (similar to http-gw) for the `HeadBucket` response. To see the headers, you need to pass the `--debug` flag (using the aws cli).
