### ISSUE TITLE
Relsove object version order during the single gate access

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-s3-gw#242]
> Are there any tests in `s3-tests` for that?

There is `s3tests_boto3.functional.test_s3:test_versioned_object_acl` test but we couldn't use it. This test fails on versioning checking since objects are created in the same epoch and their versions are out of order.

_Originally posted by @KirillovDenis in https://github.com/nspcc-dev/neofs-s3-gw/issues/239#issuecomment-908654926_

---

In theory, it seems, that in the case of single gate access, the gate should be able to resolve object version order by the order of objects in `S3-Versions-Add` list. Let's discuss it.

**Comment by realloc** [comment]
The versions list in the object attributes must already be sorted in the creation order. When a `n+1` version is created, it's appended to the list form the `n` version, hence it will be correctly maintained over time.

Hash sorting rule should be used to resolve possible conflicts in a deterministic way

**Comment by alexvanin** [comment]
> Hash sorting rule should be used to resolve possible conflicts in a deterministic way

So if there are two objects with `S3-Version-Add: [X, Y]` and `S3-Version-Add: [X, Z]`, then the latest version should be determinad by hash distance of `Y` and `Z`.

I suppose it is not the case for `s3tests_boto3.functional.test_s3:test_versioned_object_acl`, or is it? @KirillovDenis can you verify it?

**Comment by KirillovDenis** [comment]
> I suppose it is not the case for s3tests_boto3.functional.test_s3:test_versioned_object_acl, or is it?

It is. I guess there is a bug with the s3-gw version sorting mechanism.
