### ISSUE TITLE
GetObject does not work properly

### ISSUE THREAD

**Issue by EliChin** [nspcc-dev/neofs-s3-gw#261]
After an object is put, it cannot be got with GetObject (+ status issue -- `status: 0`), although this object is present in the corresponding object lists. 
```
2021-09-07T09:52:55.089Z	info	api/router.go:153	call method	{"status": 0, "request_id": "d8fbcac2-1be0-4f22-966c-a6acbc212e52", "method": "GetObject", "description": ""}
2021-09-07T09:52:55.110Z	warn	layer/object.go:610	couldn't get versioning settings object	{"error": "NoSuchKey: 404 => The specified key does not exist."}
```

**Comment by KirillovDenis** [comment]
How did you check that object couldn't be retrieved: file just doesn't appear after `GetObject` invocation (empty payload in http response)  or there are some errors in http response? Also could you provide version of s3-gw?

**Comment by EliChin** [comment]
Version used: v0.17.0-rc.1-15-g19b917e

The steps in the test are the following:
an object is generated;
the object is put in a bucket;
a list of object is made, and this list contains this certain object;
while trying to get the object, the status of `GetObject` is 0, which may be wrongly interpreted by the test;
the test fails for the object is not copied [issue#260](https://github.com/nspcc-dev/neofs-s3-gw/issues/260) and not found for deletion.

The problem may be associated with the object itself. However, there are no errors concerning file generation.

**Comment by KirillovDenis** [comment]
Actually status returned to the client is 200. It's wrong logs but it shouldn't affect the test.
