### ISSUE TITLE
Bucket cannot be deleted

### ISSUE THREAD

**Issue by KirillovDenis** [nspcc-dev/neofs-s3-gw#309]
After deleting bucket we still can find and use it (e.g. `Head Bucket` request is successful). The reason is we still can find container id in NNS contract.

Check the following tests:
* `test_s3.test_object_raw_get_bucket_gone`
* `test_s3.test_object_delete_key_bucket_gone`
* `test_s3.test_atomic_write_bucket_gone`

/cc @alexvanin

**Comment by alexvanin** [comment]
Container removal requires Alphabet node approval. If `Head Bucket` request happens immediately, then we may see such behaviour.

Is removed container (bucket) available in container contract, though? The record in NNS contract [should be removed](https://github.com/nspcc-dev/neofs-contract/blob/f5531561b86609ddfcad4f72313f5b11d2d0ded0/container/container_contract.go#L349) together with data from container contract. 

Maybe Alphabet node didn't approve container removal for some reason.

**Comment by KirillovDenis** [comment]
It is not a bug. The reason of failure is using wrong container session token (for `PUT` rather than `DELETE`).

But currently we cannot issue access box with multiple container session token. Maybe we should support it.

**Comment by alexvanin** [comment]
> I think it would be nice to be able to use the same credential for creating and deleting bucket. Maybe we should support it.

Agree with you. Session token intentionally doesn't have wildcard for the verbs, so the only choice there is to keep two or even three tokens for `PUT`, `DELETE` and `SETEACL` [operations](https://github.com/nspcc-dev/neofs-api/blob/d9d71ccd662dd9681f0fab51e647ea4864510225/session/types.proto#L50-L62)

**Comment by KirillovDenis** [comment]
Since it isn't a bug the issue is closed.
The further container session token discussion #329
