### ISSUE TITLE
Authmate default container name

### ISSUE THREAD

**Issue by KirillovDenis** [nspcc-dev/neofs-s3-gw#324]
When we run `authmate issue-secret` without specific container id, new one will be created. It we don't specify `--container-friendly-name` key the default name `auth-container` will be used. After #299 container friendly name became system name. But because of container name has to be unique we will get the following error (if someone already create container with default `auth-container` name):

`failed to issue secret: status: code = 1024 message = could not handle request: could not execute Put request: could not invoke method (putNamed): chain/client: contract execution finished with state FAULT; exception: at instruction 3509 (THROW): unhandled exception: "name is already taken"`

So we should use default container name that has format `auth-container-{random}` or `auth-container-{timestamp}`.

**Comment by KirillovDenis** [comment]
Or maybe we shouldn't use default container name at all

**Comment by realloc** [comment]
Is it possible to use the CID directly without friendly names in those cases?

**Comment by KirillovDenis** [comment]
Yes, it is.
