### ISSUE TITLE
Authmate: update default session token rules 

### ISSUE THREAD

**Issue by KirillovDenis** [nspcc-dev/neofs-s3-gw#336]
After https://github.com/nspcc-dev/neofs-node/issues/1110 we cannot create bucket using credentials only with `PUT` container session token. Even if we use default bucket acl policy `neofs-s3-gw` set up minimal eACL table that allows everything to owner and denies everything for others (it requires `SetEACL` token).

So we need to update documentation and highlight requirement to have two session tokens (`PUT`, `SetEACL`) if user want to create buckets. And change default tokens (currenltly it's only for `PUT` operations).

We cannot allow to create bucket without eACL because it's insecure. (To work with bucket we have bearer token that based on  eACL restrictions)

**Comment by alexvanin** [comment]
I suggest also update defaults and create maybe all three session tokens: for `PUT`, `SetEACL` and `DELETE`.
