### ISSUE TITLE
The gateway hangs when a user tries to create a bucket with session token without SetEACL permission

### ISSUE THREAD

**Issue by masterSplinter01** [nspcc-dev/neofs-s3-gw#347]
When a user with session token with only PUT permission tries to create a bucket, the GW does the following steps: 
1. puts container successfully
2. tries to put eacl, but receives the error:
```
could not handle request: could not execute GetEACL request: extended ACL table is not set for this container
```
and returns 500 Internal Error to the user. 

Then AWS CLI retries to create the bucket again and receives `name is already taken` error because containers with that name is already created (see p. 1)

**Comment by alexvanin** [comment]
I guess gateway can ignore setting eACL stage if token is missing?

**Comment by masterSplinter01** [comment]
Maybe we should check the session token before creating a container? Because it seems odd that we permissions to `PUT` **and** `SETEACL` to create a bucket require (e.g. in authmate readme), but a user can create a container without `SETEACL` permission?
