### ISSUE TITLE
Waiting for eACL table change may not work correctly

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-s3-gw#365]
## Overview
In current implementation `layer.waitEACLPresence` method waits for eACL table persisting through binary comparison of sent and read tables. This approach may not be correct:

1. the system _currently_ does not guarantee the binary safety of the table;
2. there can be a 3rd eACL table because of possible parallel modifications.

## Possible solution

- preliminary read latest eACL table from the network and serialize it;
- serialize sent table;
- perform polling and compare both sent and initially read tables.

**Comment by alexvanin** [comment]
We can define `EqualTo` method on eACL table which compares rules and not the form of the eACL message.

**Comment by alexvanin** [comment]
I propose to make a bench on comparing binary data and parsed structures. If later is not overwhelmly worse, then we can implement it in pool + SDK as `WaitForEACLPresense`.

**Comment by KirillovDenis** [comment]
See draft with benchmarks https://github.com/nspcc-dev/neofs-sdk-go/pull/180 in sdk
