### ISSUE TITLE
Bucket removal can behave incorrectly

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-s3-gw#366]
In current implementation bucket removal produces container removal https://github.com/nspcc-dev/neofs-s3-gw/blob/44548212858db1d13a27c9b89cfe55041cde1e00/api/layer/container.go#L241.
This operation is not synchronous. I didn't catch any implementation requirements in docs, so may be we need to make sync operation and await for the actual removal (like in bucket creation).

**Comment by alexvanin** [comment]
Maybe it was hard to find in tests, because neofs-dev-env has 1 sec block, so removal happens almost immediate. But in production we won't have 1 sec blocks.
