### ISSUE TITLE
Use NeoFS SDK functionality to handle API errors

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-s3-gw#367]
In current implementation we check NeoFS API status returns via string comparison:
https://github.com/nspcc-dev/neofs-s3-gw/blob/44548212858db1d13a27c9b89cfe55041cde1e00/api/layer/object.go#L665

That was a temporary solution because of lack of the status returns in NeoFS API protocol.
* After  https://github.com/nspcc-dev/neofs-sdk-go/pull/140 we can use native SDK functionality. 

@alexvanin @KirillovDenis @masterSplinter01 pls attach more code references with same string approach if needed.

**Comment by KirillovDenis** [comment]
https://github.com/nspcc-dev/neofs-s3-gw/blob/44548212858db1d13a27c9b89cfe55041cde1e00/api/layer/object.go#L389
