### ISSUE TITLE
Use tree service for object versions

### ISSUE THREAD

**Issue by KirillovDenis** [nspcc-dev/neofs-s3-gw#413]
We can use [tree service](https://github.com/nspcc-dev/neofs-node/pull/1324) to store versions after #407 will be merged.

### Versioning enabled
1. Put object into NeoFS
2. `AddByPath` with meta that contains attributes `[FileName, OID]`

### Versioning suspended
1. `GetNodeByPath` with meta that contains attributes `[OID, IsUnversioned]`
2. Put object into NeoFS
3. `AddByPath` with meta that contains attributes `[FileName, OID, IsUnversioned]`
4. Remove objects (which was got in step 1 and had attribute `IsUnversioned`) from NeoFS and tree service (invoke `Remove` method)

### If version id isn't provided
1. `GetNodeByPath` with flag (only last version) and meta that contains attributes `[OID]`
2. Check attribute `IsDeleteMark`. If it exists return `not found` error.
3. Get/Head object from NeoFS

### If version is provided and not `null`
1. `GetNodeByPath` with meta that contains attributes `[OID]`
2. Check that result from step 1 contains the required version
3. Check attribute `IsDeleteMark`. If it exists return `not found` error.
4. Get/Head object from NeoFS

### If provided version is `null`
1. `GetNodeByPath` with meta that contains attributes `[OID, IsUnversioned]`
2. Sort nodes that contains `IsUnversioned` attribute from step 1 by `timestamp` and then by `OID` and get last
3. Check attribute `IsDeleteMark`. If it exists return `not found` error.
4. Get/Head object from NeoFS
5. Remove all but last nodes from tree service (from step 2) and corresponded object from NeoFS

### If version id isn't provided or `null`
1. `GetNodeByPath` with meta that contains attributes `[OID, IsUnversioned]`
2. `AddByPath` node with meta that contains attributes `[OID, IsUnversioned, IdDeleteMarker]` (if list of nodes that contains attribute `IsUnversioned` from step 1 isn't empty)
3. `Remove` nodes from step 1 that have attribute `IsUnversioned`
3.1. Delete corresponded objects from NeoFS 

### If version is provided and not `null`
1. `GetNodeByPath` with meta that contains attributes `[OID, IsUnversioned]`
2. Check that result from step 1 contains the required version and it hasn't attribute `IsUnersioned`
3. `Remove` corresponded node from the tree service
4. Delete object from NeoFS

**Comment by alexvanin** [comment]
Closed in #440
