### ISSUE TITLE
Drop `updateCRDT2PSetHeaders` for system object

### ISSUE THREAD

**Issue by KirillovDenis** [nspcc-dev/neofs-s3-gw#414]
We can use [tree service](https://github.com/nspcc-dev/neofs-node/pull/1324) and drop using `updateCRDT2PSetHeaders` for system objects after #407 will be merged.

## Put system object

1. Put object into NeoFS
2. `AddByPath` specify `SystemName` to build path meta that contains attributes `[FileName, OID]`

## Get system object
1. `GetNodeByPath` specify flag (only last version), attribute `SystemName` to build path and meta that contains attributes `[OID]`
2. Get/Head object from NeoFS

**Comment by alexvanin** [comment]
Done in #440
