### ISSUE TITLE
Use the tree service for BucketNotificationConfiguration

### ISSUE THREAD

**Issue by KirillovDenis** [nspcc-dev/neofs-s3-gw#418]
We can use [tree service](https://github.com/nspcc-dev/neofs-node/pull/1324) to handle versions of BucketNotificationConfiguration after #407 will be merged.

Use `bucket-notifications` as `SystemName`

## GetBucketNotificationConfiguration
1. `GetNodeByPath` with flag (to get only last version), `SystemName` (to build path) and with attributes `[OID]`
2. Get object from NeoFS

## PutBucketNotificationConfiguration
1. `GetNodeByPath` using `SystemName` (to build path) and with attributes `[OID]`
2. Put object into NeoFS
3. `Add` to root node with attributes `[SystemName, OID]`
4. Delete objects from NeoFS that corresponds node from step 1
5. `Remove` for all nodes from step 1

**Comment by alexvanin** [comment]
Done in #429
