### ISSUE TITLE
Use the tree service for CORS

### ISSUE THREAD

**Issue by KirillovDenis** [nspcc-dev/neofs-s3-gw#419]
We can use [tree service](https://github.com/nspcc-dev/neofs-node/pull/1324) to handle versions of object with CORS  after #407 will be merged.

Use `bucket-cors` as `SystemName`

## GetBucketCors
1. `GetNodeByPath` with flag (to get only last version), `SystemName` (to build path) and with attributes `[OID]`
2. Get object from NeoFS

## PutBucketCors
1. `GetNodeByPath` using `SystemName` (to build path) and with attributes `[OID]`
2. Put object into NeoFS
3. `Add` to root node with attributes `[SystemName, OID]`
4. Delete objects from NeoFS that corresponds node from step 1
5. `Remove` for all nodes from step 1

## DeleteBucketCors
1. `GetNodeByPath` using `SystemName` (to build path) and with attributes `[OID]`
2. Delete objects from NeoFS that corresponds node from step 1
3. `Remove` for all nodes from step 1

**Comment by alexvanin** [comment]
Done in #429
