### ISSUE TITLE
Remove `layer/neofs` package

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-s3-gw#438]
https://github.com/nspcc-dev/neofs-s3-gw/commit/13080d6d969a8e858a73f7bfac53327bf3b08b4f introduced `layer/neofs` package to avoid cycle dependencies. They all gone now, so we can drop this extra package to keep only one `neofs` pkg in `internal/neofs`.

**Comment by KirillovDenis** [comment]
It seems the cycle dependency in tests.

**Comment by KirillovDenis** [comment]
Consider approach like https://github.com/nspcc-dev/neofs-s3-gw/pull/473#discussion_r885531054
