### ISSUE TITLE
Optimize PUT

### ISSUE THREAD

**Issue by KirillovDenis** [nspcc-dev/neofs-s3-gw#441]
Let's add an issue to optimize this code in the future. I think we can avoid object.Head RPC for the object we put into NeoFS in 10 code lines before.

_Originally posted by @alexvanin in https://github.com/nspcc-dev/neofs-s3-gw/pull/440#discussion_r876727249_

**Comment by alexvanin** [comment]
As far as I noticed, mostly we need hash (for ETag) and creation epoch from the object. I think hash can be calculated on the s3-gateway side manually. Creation epoch can be fetched as well, I guess.
