### ISSUE TITLE
Cannot PUT object with name like `objectname/`

### ISSUE THREAD

**Issue by KirillovDenis** [nspcc-dev/neofs-s3-gw#444]
Currently we cannot put object with trailing slash in name

```
$ aws s3api put-object --bucket kirillov3 --key asdf/ --body data.txt

An error occurred (InternalError) when calling the PutObject operation (reached max retries: 0): couldn't add new verion to tree service: couldn't get nodes: failed to get node path: rpc error: code = Unknown desc = invalid signature
```

The reason is [here](https://github.com/nspcc-dev/neofs-s3-gw/blob/tree-service/internal/neofs/tree.go#L322). We try to set filename as empty string. We can handle such case and use special filename (e.g. `<empty>` because `<` and `>` [should be avoided in object keys](https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-keys.html) )

**Comment by alexvanin** [comment]
Is it relevant for master branch too?

**Comment by KirillovDenis** [comment]
> Is it relevant for master branch too?

No. It's relevant only for the `tree-service` branch
