### ISSUE TITLE
cache: React on cache value cast failures

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-s3-gw#465]
See discussion https://github.com/nspcc-dev/neofs-s3-gw/pull/458#discussion_r883309547.

**Comment by alexvanin** [comment]
I am okay with log message, because it will be a cache-miss and we can continue to process request. Otherwise I would go with the panic. I expect that cast failure should never happen, though.

**Comment by cthulhu-rider** [comment]
Agree, cast fails on developer (unit tests should actually cover it) or LRU lib mistakes. In both cases panic is the best way IMO.
