### ISSUE TITLE
Rebase tree-service on master

### ISSUE THREAD

**Issue by KirillovDenis** [nspcc-dev/neofs-s3-gw#470]
This should be adopted in the `tree-service` branch

_Originally posted by @KirillovDenis in https://github.com/nspcc-dev/neofs-s3-gw/issues/469#issuecomment-1140978474_

**Comment by KirillovDenis** [comment]
We can adopt only this change or make rebase. 
@alexvanin

**Comment by alexvanin** [comment]
I will do rebase after https://github.com/nspcc-dev/neofs-s3-gw/pull/467

**Comment by alexvanin** [comment]
Done in https://github.com/nspcc-dev/neofs-s3-gw/commit/c7ca803a8a5a153b9746bb36af756646a39ef917
Backup at https://github.com/alexvanin/neofs-s3-gw/tree/backup/tree-service-30-may-2022
