### ISSUE TITLE
Use appropriate `null` version

### ISSUE THREAD

**Issue by KirillovDenis** [nspcc-dev/neofs-s3-gw#474]
We should get info about `null` version from tree service rather than object header
https://github.com/nspcc-dev/neofs-s3-gw/blob/c7ca803a8a5a153b9746bb36af756646a39ef917/api/handler/object_list.go#L284

https://github.com/nspcc-dev/neofs-s3-gw/blob/c7ca803a8a5a153b9746bb36af756646a39ef917/api/data/info.go#L87-L92

**Comment by alexvanin** [comment]
Done in #481
