### ISSUE TITLE
Storing `Etag`, `Created` and `Size` near by parts in tree service

### ISSUE THREAD

**Issue by KirillovDenis** [nspcc-dev/neofs-s3-gw#475]
For now we store in the tree node the following part info:
* PartNumber
* OID

We can extent these attributes to:
* PartNumber
* OID
* Etag/Hash
* Size
* Created

It can reduce the number of `head` requests during `CompleteMultipart`, `AbortMultipart`, `ListPart` opeations:
https://github.com/nspcc-dev/neofs-s3-gw/blob/c7ca803a8a5a153b9746bb36af756646a39ef917/api/layer/multipart_upload.go#L531-L570

**Comment by alexvanin** [comment]
Don't see any issues with that. These attributes are quite small so it should be okay to store them in the tree service.
