### ISSUE TITLE
Passing and returning ID types of NeoFS SDK

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-s3-gw#488]
Define how we handle basic SDK types in code, by pointer, by value, mixed. Sync it everywhere in the code.

Types:
- `oid.ID`
- `cid.ID`
- `oid.Address`
- `user.ID`

---

It depends on the approach taken: return `(T, error)` or `(*T, error)`. IMO first is expected to improve performance (but it's compilator-dependent) while latter is easier to read. We have same discussion in neofs-node https://github.com/nspcc-dev/neofs-node/pull/1418#discussion_r880087590.

I suggest you also discuss, if you decide to return by value - let me know and I'll change.

_Originally posted by @cthulhu-rider in https://github.com/nspcc-dev/neofs-s3-gw/pull/458#discussion_r882371570_

**Comment by alexvanin** [comment]
I would treat these types as native types: pass by value, return by value. The only exceptions are caches, where getters return pointers, because `nil` value considered as a cache miss. Can be refactored to return `(T, bool)` with low priority.

**Comment by cthulhu-rider** [comment]
Related but not directly.

In latest SDK all these types can be used as `map` keys. I've locally tried to test mapping by types instead of string in caches.

 ```
    goos: linux
    goarch: amd64
    pkg: github.com/nspcc-dev/neofs-s3-gw/api/cache
    cpu: Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
    
    AccessBoxCache-8    8.54µs ± 6%  1.98µs ±10%  -76.77%  (p=0.000 n=9+9)
    ObjectsCache-8      11.0µs ± 8%  3.1µs ±13%   -71.51%  (p=0.000 n=10+10)
    AccessBoxCache-8    753B ± 0%    273B ± 0%    -63.75%  (p=0.000 n=9+9)
    AccessBoxCache-8    15.0 ± 0%    5.0 ± 0%     -66.67%  (p=0.000 n=10+10)
    ObjectsCache-8      1.14kB ± 0%  0.42kB ± 0%  -62.94%  (p=0.000 n=10+10)
    ObjectsCache-8      23.0 ± 0%    8.0 ± 0%     -65.22%  (p=0.000 n=10+10)
    ObjectsListCache-8  179µs ± 9%   235µs ±17%   +31.49%  (p=0.000 n=10+10)
    ObjectsListCache-8  464B ± 0%    320B ± 0%    -31.03%  (p=0.000 n=10+10)
    ObjectsListCache-8  12.0 ± 0%    8.0 ± 0%     -33.33%  (p=0.000 n=10+10)
```

if it looks worthwhile I can post a PR.

**Comment by KirillovDenis** [comment]
Done in #556
