### ISSUE TITLE
Support ACL operations via translation to eACL request with Session Token

### ISSUE THREAD

**Issue by realloc** [nspcc-dev/neofs-s3-gw#49]
S3 API has [ACL support](https://docs.aws.amazon.com/AmazonS3/latest/userguide/acl-overview.html). Most of it can be translated into NeoFS eACL. The proposal is to convert S3 ACL changes into NeoFS eACL inside S3 Protocol Gateway and sen NeoFS API gRPC requests attaching Session Token with container Context defined.

**Comment by KirillovDenis** [comment]
Aws acl has the following [format](https://docs.aws.amazon.com/AmazonS3/latest/userguide/acl-overview.html):
```
<AccessControlList>
<Grant>
    <Grantee>
        <DisplayName>string</DisplayName>
        <EmailAddress>string</EmailAddress>
        <ID>string</ID>
        <xsi:type>Group|CanonicalUser|emailAddress</xsi:type>
        <URI>string</URI>
    </Grantee>
    <Permission>FULL_CONTROL|WRITE|WRITE_ACP|READ|READ_ACP</Permission>
</Grant>
</AccessControlList>
```

For a start we can use the following permissions:
1. FULL_CONTROL - all neofs operations
2. WRITE - `Put` and `Delete` operations
2. READ - operations other than 'Put` and `Delete`

and types:
1. CanonicalUser - use public key as id (and map it to target with `User` role and key)
2. Group - support only `http://acs.amazonaws.com/groups/global/AllUsers` group (map to `Others` neofs role)

But to support such `CanonicalUser`  we need to change content of `Owner` struct (need change owner id to public key or use some tool to such translation)
