### ISSUE TITLE
Provide NodeVersion to GetObjectTaggingAndLock method

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-s3-gw#490]
Actually we can go further and save one more request to the tree service (getting `*data.NodeVersion`). Currently we do this twice: in `layer.GetObjectInfo` and in `layer.GetObjectTaggingAndLock`. But this requires significant refactoring.
We can consider this as a separate issue though.

_Originally posted by @KirillovDenis in https://github.com/nspcc-dev/neofs-s3-gw/issues/480#issuecomment-1144596703_

**Comment by alexvanin** [comment]
It can be done relatively simple by having `*TreeNode` field in `data.ObjectInfo`. Then `layer.headLastVersionIfNotDeleted()` and `layer.headVersion()` can set `TreeNode` field of `data.ObjectInfo` so we can reuse it in `layer.GetObjectTaggingAndLock()`.

But there are more places where `data.ObjectInfo` is returned, e.g. `layer.PutObject()`. In this case I would like to set `TreeNode` in `data.ObjectInfo` structure inside `layer.PutObject()` as well (even though it won't be used yet). If I am not mistaken, `layer.PutObject()` doesn't always have `NodeVersion` structure to return. If object is new, or it is new version, it calls `addNodeByPath` and that's it. :thinking:

**Comment by KirillovDenis** [comment]
Done in #561
