### ISSUE TITLE
Bearer token must be signed by the container owner

### ISSUE THREAD

**Issue by KirillovDenis** [nspcc-dev/neofs-s3-gw#504]
Node version https://github.com/nspcc-dev/neofs-node/commit/4a50bdfa008fefe139eabdf2bebf6899c1f53de1

* s3tests_boto3.functional.test_s3:test_object_copy_not_owned_bucket
* s3tests_boto3.functional.test_s3:test_access_bucket_private_object_private
* s3tests_boto3.functional.test_s3:test_access_bucket_private_objectv2_private

related to #501

**Comment by alexvanin** [comment]
NeoFS Node Tree Service is not ready to work with anonymous requests, blocked.
