### ISSUE TITLE
Lock errors

### ISSUE THREAD

**Issue by KirillovDenis** [nspcc-dev/neofs-s3-gw#509]
Node version https://github.com/nspcc-dev/neofs-node/commit/4a50bdfa008fefe139eabdf2bebf6899c1f53de1

The problem seems to be similar to https://github.com/nspcc-dev/neofs-node/pull/1472/commits 
* s3tests_boto3.functional.test_s3:test_object_lock_get_obj_retention
* s3tests_boto3.functional.test_s3:test_object_lock_get_obj_retention_iso8601
* s3tests_boto3.functional.test_s3:test_object_lock_get_obj_metadata
* s3tests_boto3.functional.test_s3:test_object_lock_uploading_obj

Test tries to remove locked object using bypass (in NeoFS the lock cannot be deleted):
* s3tests_boto3.functional.test_s3:test_object_lock_put_obj_retention_versionid

Test tries to short the until date (in NeoFS the lock cannot be deleted):
* s3tests_boto3.functional.test_s3:test_object_lock_put_obj_retention_shorten_period_bypass

related to #501

**Comment by KirillovDenis** [comment]
The following tests will fail anyway because they try to delete object (that is locked) but NeoFS doesn't allow this.
* s3tests_boto3.functional.test_s3:test_object_lock_get_obj_retention
* s3tests_boto3.functional.test_s3:test_object_lock_get_obj_retention_iso8601
* s3tests_boto3.functional.test_s3:test_object_lock_get_obj_metadata
* s3tests_boto3.functional.test_s3:test_object_lock_uploading_obj

But there is another problem: missed retention lock info if both lock types are provided.
We need use `if` instead of `else if`
https://github.com/nspcc-dev/neofs-s3-gw/blob/8f23f4fbc41ec2a42523a2883bd81ff9d4152807/internal/neofs/tree.go#L910

**Comment by KirillovDenis** [comment]
I suppose we can close this issue by marking tests as failed (in compatibility table). Or we can postpone this if the lock removal policy will be changed

**Comment by alexvanin** [comment]
Try these tests on master branch. Just wonder if they gonna fail too.

**Comment by KirillovDenis** [comment]
Some of this tests pass on `master` branch because of https://github.com/nspcc-dev/neofs-s3-gw/blob/0e27fea8f21c0f104f8fbf1d6bfda244e6b8b344/api/handler/delete.go#L89-L92 `IsErrObjectLocked` doesn't work as expected.
https://github.com/nspcc-dev/neofs-s3-gw/blob/0e27fea8f21c0f104f8fbf1d6bfda244e6b8b344/api/handler/delete.go#L143-L151

In `tree-service` branch this was fixed
https://github.com/nspcc-dev/neofs-s3-gw/blob/575947e03567506d1713328430c038fc6763b077/api/handler/delete.go#L144-L152
