### ISSUE TITLE
Drop `tree.service` config parameter

### ISSUE THREAD

**Issue by KirillovDenis** [nspcc-dev/neofs-s3-gw#511]
Currently, the `tree` service in node listens  the same port as the `object` service so we can drop the `tree.service` config param.

But we have to think about something like a pool for `tree-service` clients in s3. To start we can use the first node endpoint from the `peers` config section

**Comment by alexvanin** [comment]
Blocked by SDK adoption.

**Comment by roman-khimov** [comment]
It will be dropped, but in a bit different manner, along with the whole tree service. This specific issue is irrelevant.
