### ISSUE TITLE
Should the container created by the authmate be `STICKY`?

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-s3-gw#540]
I noticed that authmate creates containers with set `STICKY` flag:
https://github.com/nspcc-dev/neofs-s3-gw/blob/1012a3c6a418183bdf75d50b30f0bdc6260977ec/internal/neofs/neofs.go#L550-L557

Is it expected?

If yes, I suggest to mention it in method docs
https://github.com/nspcc-dev/neofs-s3-gw/blob/1012a3c6a418183bdf75d50b30f0bdc6260977ec/authmate/authmate.go#L71

**Comment by alexvanin** [comment]
It is not expected. It does not provide any value there, so sticky bit is redundant.
