### ISSUE TITLE
Tagging notifications in tree service

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-s3-gw#546]
In tree service branch, we can't use `objInfo` structure in notifications like we do on master branch after https://github.com/nspcc-dev/neofs-s3-gw/commit/bd5fd041b7597747649cd5a9ae39b18318a149ef. The reason is that object tagging does not involve operations in object service anymore.

I have a couple proposals.

1. Do not use `data.ObjectInfo` in `SendNotificationsParams`. Notification uses only a [small subset of fields](https://github.com/nspcc-dev/neofs-s3-gw/blob/8a1fc8ae3f99cff5dc060d969a384e94e109ec1f/api/notifications/controller.go#L243-L246) from `ObjectInfo`: name, size, version, etag (hash). Those can be defined in a separate structure which can be built based on `ObjectInfo` or from scratch.

2. Specify version in tagging notifications. Version is available in request. Without (1) we have to parse version into object.ID and then set it in `ObjectInfo`. After (1) we can set version string directly.

3. Check what field actually need to be specified. In some notifications like delete notifications we avoid size and etag. I guess it is okay, but can we avoid this info in tagging notifications?

**Comment by KirillovDenis** [comment]
It seems it's one more case where we want to store `size` and `etag` in tree service.

**Comment by alexvanin** [comment]
Blocked the same as https://github.com/nspcc-dev/neofs-s3-gw/issues/533#issuecomment-1157524328

**Comment by alexvanin** [comment]
Unblocked due to https://github.com/nspcc-dev/neofs-s3-gw/pull/536#issuecomment-1186941185
