### ISSUE TITLE
Anonymous bucket listing may return non empty result

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-s3-gw#548]
1. Create buckets
2. Make anonymous listing
3. See buckets (why?)

It may happen when user shares a key with S3 Gateway. Need to check.

**Comment by KirillovDenis** [comment]
Couldn't reproduce. I always get the empty list. Random key is always used so sharing a key with S3 Gateway doesn't change anything. Perhaps the problem was fixed in some update.

**Comment by alexvanin** [comment]
@KirillovDenis is it true for both `tree-service` and `master` branch?

**Comment by KirillovDenis** [comment]
> @KirillovDenis is it true for both `tree-service` and `master` branch?

Yes

**Comment by alexvanin** [comment]
Then closed until proper reproduction steps.
