### ISSUE TITLE
Common region-policy settings

### ISSUE THREAD

**Issue by realloc** [nspcc-dev/neofs-s3-gw#568]
One can define AWS region mapping to storage policy in authbox, but we also need a way to setup a default region set in config or in some external config source.

With this feature app developers could use a known set of regions without diving into policy creation specifics.

**Comment by alexvanin** [comment]
As far as I understand, AWS client uses region value to define subset of allowed RPC requests. NeoFS S3 Gateway implements the same API in all installments (at least for now).

So storage policy is related to container policy. What region is related to in terms of NeoFS storage?

**Comment by realloc** [comment]
Currently, we get storage policy from the table in authbox using region set in `LocationConstraint` as a mapping key at bucket creation time. We could simplify operations a lot by sharing that mapping or providing some common list.

**Comment by alexvanin** [comment]
> operations a lot by sharing that mapping

Provide region -> default container policy mapping in S3 Gateway config? Seems reasonable.

**Comment by realloc** [comment]
The list of regions defined in S3 GW config, like it's defined in `policy.json` for each authbox, can be used with location constraint directly from aws tools, without involving authmate operations.

For example, in case when user authentication is handled by external service, users will not need authmate and will not have a way to define custom locations. For this case we need a default list set in S3 GW for all users, while authmate users still can override it.

@alexvanin The proposal is to add the default location to policy mappings without removing existing authbox features.

**Comment by KirillovDenis** [comment]
Will we want to know placement policy by region (e.g. return this policy in headers on `HeadBucket` or `GetBucketLocation` request)? If so then we will not know what mapping is correct because we can use the different gates. While using mapping from authmate is easy because we know user credentials.

**Comment by KirillovDenis** [comment]
> Could you please clarify the question? When we create a bucket with location constraints, the region name persists in bucket meta and the storage policy persist in the container itself. The returned name + policy is always correct.

Oh, sorry. I was wrong. There is not any problem with mapping.

**Comment by alexvanin** [comment]
Reconsider this issue because we don't plan to support external auth service (at least now)

**Comment by realloc** [comment]
I'd propose to implement this as designed now. External auth doesn't impact the default region set feature.

**Comment by alexvanin** [comment]
Common policies may change over time by the will of system administrator. Access boxes are immutable, so we can't modify common policies without revoking credentials. So the best way is to specify such policies as gateway configuration.
