### ISSUE TITLE
Refactor storing of versioning setting in the tree service

### ISSUE THREAD

**Issue by masterSplinter01** [nspcc-dev/neofs-s3-gw#569]
Now we store versioning settings as two bools:
 https://github.com/nspcc-dev/neofs-s3-gw/blob/master/api/data/info.go#L48
```
BucketSettings struct {
  IsNoneStatus      bool
  VersioningEnabled bool                     `json:"versioning_enabled"`
  LockConfiguration *ObjectLockConfiguration `json:"lock_configuration"`
}
```
1. `IsNoneStatus` = true, `VersioningEnabled` = false -- unversioned (if a tree node has not been created)
2. `IsNoneStatus` = false, `VersioningEnabled` = false -- suspended
3. `IsNoneStatus`= false, `VersioningEnabled` = true -- versioned
4. `IsNoneStatus` = true, `VersioningEnabled` = true -- is not possible

Maybe we can store it as a string `Unversioned`, `Versioned`, `Suspended` or as int (line `enum`: 0 = `Unversioned`, 1 = `Versioned`, 2 = `Suspended`).

It will make code simpler. 

BUT it breaks backward compatibility.

**Comment by alexvanin** [comment]
Blocked the same as https://github.com/nspcc-dev/neofs-s3-gw/issues/533#issuecomment-1157524328

**Comment by alexvanin** [comment]
I think it is time to do that according to https://github.com/nspcc-dev/neofs-s3-gw/pull/536#issuecomment-1186941185
