### ISSUE TITLE
Make version output the same as in `neofs-node`

### ISSUE THREAD

**Issue by realloc** [nspcc-dev/neofs-s3-gw#578]
S3 Gateway currently displays its version like:
```
$ neofs-s3-gw --version
NeoFS S3 gateway v0.21.1-60-g5bfc549-dirty
```
We need to make it like in `neofs-node`, like:
```
$ neofs-node --version
Version: v0.28.3-62-g8ab72eb4 
Build: 2022-07-05T21:45:30+00:00 
Debug: false
```
Maybe we want to add `Component: NeoFS S3 Gateway` also, to help robots in parsing output.

**Comment by realloc** [comment]
Not required, but I'd be glad if we can make the whole stack behave the same way.

**Comment by fyrchik** [comment]
If we want reproducible builds, what about also providing compiler version (`Go: go1.17.3`) in the output?
