### ISSUE TITLE
Listing works only for 10 nested level

### ISSUE THREAD

**Issue by KirillovDenis** [nspcc-dev/neofs-s3-gw#624]
Currently there is a limitation of neofs-storage tree-service: max depth of subtree is 10. So we can not list object that is placed in deeper level:
```shell
$ aws s3api put-object --bucket anon4 --key a/b/c/d/e/f/g/h/i/j/k/log.txt
{
    "ETag": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "VersionId": "4BeUUNyY2Cg1GkEX1xZvH5xbYNHEUo9au3RMQFXV8PRc"
}

$ aws s3api list-objects --bucket anon4

$ aws s3api put-object --bucket anon4 --key a/b/c/d/e/f/g/h/i/j/log.txt
{
    "ETag": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "VersionId": "2TDj9tbU1Gm4a2oeE5dxMGs4YiQam6sQBzU1vfcNhpQ8"
}

$ aws s3api list-objects --bucket anon4
{
    "Contents": [
        {
            "Key": "a/b/c/d/e/f/g/h/i/j/log.txt",
            "LastModified": "2022-07-26T06:34:13+00:00",
            "ETag": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
            "Size": 0,
            "Owner": {
                "DisplayName": "NbUgTSFvPmsRxmGeWpuuGeJUoRoi6PErcM",
                "ID": "NbUgTSFvPmsRxmGeWpuuGeJUoRoi6PErcM"
            }
        }
    ]
}
```

**Comment by alexvanin** [comment]
Possible solutions:
- walk the tree with multiple `getSubTree` requests until the leafs. 
- ask storage node to return whole sub-tree in a single stream if depth == 0.

@fyrchik what do you think about latter option? As far as I remember, we had discussion about depth before `getSubTree` started to return stream. Maybe there are other issues?

**Comment by fyrchik** [comment]
Depth is needed to restrict the amount of accumulated operations in memory. We do BFS, so it is equal to the amount of nodes on a specific level. I will check if this can be avoided, in which case, the latter option would be acceptable.

**Comment by alexvanin** [comment]
> I will check if this can be avoided, in which case, the latter option would be acceptable.

Any news on that?
