### ISSUE TITLE
Configure SetCopiesNumber in NeoFS requests

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-s3-gw#634]
Blocked by https://github.com/nspcc-dev/neofs-sdk-go/issues/302

**Comment by KirillovDenis** [comment]
Let's add the new config param `neofs.set_copies_number` with default value `0` (it means omitting params and should lead to default neofs-storage behavior) and will use it as `SetCopiesNumber` param when put object to NeoFS
