### ISSUE TITLE
Reconsider using eacl filters by object name 

### ISSUE THREAD

**Issue by KirillovDenis** [nspcc-dev/neofs-s3-gw#642]
Currently, eacl filters by user defined attribute (e.g. attribute `FileName` - object name) works only for small object. We should reconsider using such filters (maybe drop)

**Comment by carpawell** [comment]
If an object gonna be split (or even if not), add to it a well-known system attribute that will make the SNs add all the "important" attributes to all the child objects.

Blocked by:
- [ ] https://github.com/nspcc-dev/neofs-api/issues/236
- [ ] https://github.com/nspcc-dev/neofs-sdk-go/issues/313
- [ ] https://github.com/nspcc-dev/neofs-node/issues/1676

**Comment by roman-khimov** [comment]
Irrelevant with v2 split (https://github.com/nspcc-dev/neofs-api/pull/283).
