### ISSUE TITLE
Optimize creating locks and tags

### ISSUE THREAD

**Issue by KirillovDenis** [nspcc-dev/neofs-s3-gw#669]
Currently, when we do `PutObject` or `CopyObject` with tags or locks we do extra requests to the tree-service 
https://github.com/nspcc-dev/neofs-s3-gw/blob/a2178713347a64bc4daf80036d7342961e43d499/api/handler/put.go#L278
https://github.com/nspcc-dev/neofs-s3-gw/blob/a2178713347a64bc4daf80036d7342961e43d499/api/layer/object.go#L268

We can optimize this (e.g. remember node id after add version)

**Comment by alexvanin** [comment]
PutLockInfo has been optimized. PutObjectTagging is up to go.
