### ISSUE TITLE
Fix test_get_obj_head_tagging

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-s3-gw#682]
This simple test is failing. 
1) Upload object
2) Set two tags
3) Head object and check `x-amz-tagging-count` header == `2`

The reason is hidden in #577. After this PR at object put we cache `ExtendedObjectInfo`, which contains `NodeVersion`.
https://github.com/nspcc-dev/neofs-s3-gw/blob/163038b37d90e9fe17286bc450a573c8e2320107/api/layer/object.go#L289-L294

This `NodeVersion` is missing `ID` field. It isn't set because it is never returned from tree service in the first place.
https://github.com/nspcc-dev/neofs-s3-gw/blob/163038b37d90e9fe17286bc450a573c8e2320107/internal/neofs/tree.go#L1343

The same `NodeVersion` is going to be read from cache and used in head request.
https://github.com/nspcc-dev/neofs-s3-gw/blob/163038b37d90e9fe17286bc450a573c8e2320107/api/handler/head.go#L78

In the end we got here with `objVersion.ID == 0` which is incorrect.
https://github.com/nspcc-dev/neofs-s3-gw/blob/163038b37d90e9fe17286bc450a573c8e2320107/internal/neofs/tree.go#L1034

## Solutions

1) Keep caching only ObjectInfo without NodeVersion.
2) Get latest version from tree service, set it in `NodeVersion` of `ExtendedObjectInfo` **and then** store in cache.
3) Try to set ID in `NodeVersion` with return value of `tree.AddByPath`.

**Comment by KirillovDenis** [comment]
I prefer the 3 option because of https://github.com/nspcc-dev/neofs-s3-gw/issues/669
