### ISSUE TITLE
Reconsider test_object_copy_to_itself

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-s3-gw#683]
According to s3-tests, copy object to itself should be [prohibited](https://github.com/nspcc-dev/s3-tests/blob/7e8e339804913f02eb2d7c23940738b3e9cc0428/s3tests_boto3/functional/test_s3.py#L6441-L6451) (unless you change tags, see `test_object_copy_to_itself_with_metadata`).

However I don't see any restrictions in the AWS spec and it seems like actual AWS allows it.

**Comment by KirillovDenis** [comment]
Actually, we cannot copy object to itself only for `unversioned` buckets

**Comment by alexvanin** [comment]
Then we can consider it as a bug, right?
