### ISSUE TITLE
Gateway requires tree service endpoint to be set but does not yell at its absence

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-s3-gw#699]
## Context
I run `neofs-s3-gw` for test purposes. I forgot to configure tree service endpoint (didn't see the requirements to set it). App successfully started, and I observed the problem during object storing:
```
aws s3api put-object --bucket <bkt_name> --key <obj_name> --body </path/to/body> --endpoint-url <gw_endpoint>

An error occurred (InternalError) when calling the PutObject operation (reached max retries: 2): couldn't get node: couldn't get nodes: failed to get node path: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: missing address"
```

## Expected behavior
App doesn't start with unspecified tree endpoint or falls back to using the NeoFS API endpoints.

## Current behavior
App successfully starts and later fails during request processing.

## Versions
neofs-s3-gw: **v0.23.0**

**Comment by alexvanin** [comment]
Blocked by decision on https://github.com/nspcc-dev/neofs-node/issues/1768

**Comment by alexvanin** [comment]
Unblocked by https://github.com/nspcc-dev/neofs-node/pull/1862
