### ISSUE TITLE
Check usage of `time.Time`

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-s3-gw#726]
Same as https://github.com/nspcc-dev/neofs-http-gw/issues/214

**Comment by KirillovDenis** [comment]
Currently, we use time.Time in the following cases:

* To set compute object attribute `__NEOFS__EXPIRATION_EPOCH` (for locks, accessbox)
* To check if [presigned url](https://docs.aws.amazon.com/AmazonS3/latest/userguide/PresignedUrlUploadObject.html) or [post policy](https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-HTTPPOSTConstructPolicy.html#sigv4-HTTPPOSTExpiration) are expired
* To check preconditions according to object `Timestamp` attribute
* Show creation time of bucket and object (based on `Timestamp` attribute)

**Comment by alexvanin** [comment]
1. See (4) in https://github.com/nspcc-dev/neofs-http-gw/issues/214
2. Try on real environment where client and S3 gateway have different time
3. Let's try to work with intervals, maybe we can do something with it
4. Nothing to do

--- 

The real blocker for us is (2). So let's focus on it here.

Also we can use block time in case if system time went off too much. 

```
if block received in threshold &&  | block time - system time | > threshold => use block time
```

**Comment by KirillovDenis** [comment]
2. Checked on real environment
As expected with presigned url we get Access denied error when s3-gw have a time in the future
```
ноя 07 14:11:57 az neofs-s3-gw[14713]: 2022-11-07T14:11:57.755Z        info        api/router.go:162        call method        {"status": 200, "request_id": "6dd9c883-54de-48e7-b854-44f498cf7d97", "method": "GetObject", "bucket": "dkirillov", "object": "obj2", "description": "OK"}

ноя 07 16:00:14 az neofs-s3-gw[14713]: 2022-11-07T16:00:14.286Z        error        api/user_auth.go:30        failed to pass authentication        {"error": "AccessDenied: 403 => Request has expired"}
```
