### ISSUE TITLE
Configure stream timeout

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-s3-gw#750]
Add new configuration parameter for https://github.com/nspcc-dev/neofs-sdk-go/issues/364

**Comment by KirillovDenis** [comment]
Also here
https://github.com/nspcc-dev/neofs-s3-gw/blob/8f1bbb7dc10476741bb7ced9eed35ce8bc672312/cmd/s3-gw/app.go#L253
we should use `prm.SetHealthcheckTimeout(healthCheckTimeout)`

**Comment by alexvanin** [comment]
Done in #751
