### ISSUE TITLE
internal neofs services `tree` package not found

### ISSUE THREAD

**Issue by rkonfj** [nspcc-dev/neofs-s3-gw#769]
https://github.com/nspcc-dev/neofs-s3-gw/blob/74f31c31498f397ee415f92d1883349c8400947c/internal/neofs/tree.go#L17

Has it been removed?

**Comment by roman-khimov** [comment]
See `syncTree.sh` kludge which is executed on `make`.

**Comment by rkonfj** [comment]
> See `syncTree.sh` kludge which is executed on `make`.

Haha, looks like a hacker's trick.
