### ISSUE TITLE
Update to SDK 1.0.0-rc.8

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-s3-gw#774]
Using outdated SDK is no good, upgrade!

**Comment by roman-khimov** [comment]
Fix nspcc-dev/neofs-sdk-go#231 along the way (`api/handler/acl.go`).

**Comment by smallhive** [comment]
> Fix [nspcc-dev/neofs-sdk-go#231](https://github.com/nspcc-dev/neofs-sdk-go/issues/231) along the way (`api/handler/acl.go`).

updated
