### ISSUE TITLE
 docker is intendent to run app not OS

### ISSUE THREAD

**Issue by 532910** [nspcc-dev/neofs-s3-gw#788]
binaries are static:

```
neofs-s3-authmate-linux-amd64:
	not a dynamic executable
neofs-s3-gw-linux-amd64:
	not a dynamic executable
```

alpine and bash are not required, please remove them from docker image

**Comment by roman-khimov** [comment]
There are certificates installed there as well, dropping them might affect the app (authmate for sure).

**Comment by 532910** [comment]
Certificates are ok if they are required.
