### ISSUE TITLE
Cannot S3 Delete objects

### ISSUE THREAD

**Issue by vvarg229** [nspcc-dev/neofs-s3-gw#799]
Test `test_s3_api_object` failed on step "Delete objects S3":
```
COMMAND: 'S3 Delete objects result'
OUTPUT:
 {
    "Errors": [
        {
            "Code": "BadRequest",
            "Key": "def51eee-67fc-4b5c-85da-89236518ab22",
            "Message": "mark object removal via connection pool: failed to collect relatives: failed to get raw object header: read object header via client: status: code = 2049 message = object not found"
        }
    ],
    "ResponseMetadata": {
        "HTTPHeaders": {
            "content-length": "400",
            "content-type": "text/xml; charset=utf-8",
            "date": "Sat, 15 Jul 2023 10:29:10 GMT",
            "x-amz-request-id": "693b370b-452f-433d-b69a-d30090798b2b"
        },
        "HTTPStatusCode": 200,
        "HostId": "",
        "RequestId": "693b370b-452f-433d-b69a-d30090798b2b",
        "RetryAttempts": 0
    }
}
```

It's look like a part of https://github.com/nspcc-dev/neofs-node/issues/2440

See result and logs:
https://http.t5.fs.neo.org/86C4P6uJC7gb5n3KkwEGpXRfdczubXyRNW5N9KeJRW73/204-1689413727/index.html#suites/cbd00784275866c60aa75f3c0d6ab31f/e455fb25910bb99c/

Environment:
neo-go version 0.101.1
neofs-s3-authmate version v0.27.1
neofs-s3-gw version v0.27.1
neofs-adm version fc824ee9
neofs-ir version c824ee9
neofs-lens version fc824ee9
neofs-cli version fc824ee9
aws-cli/2.13.0
Python/3.11.4
Linux/5.15.0-1041-azure exe/x86_64.ubuntu.22 prompt/off

**Comment by smallhive** [comment]
The original error, from the issue description, should be found in _Tear down_ tag inside the allure report.
[allure report](https://github.com/nspcc-dev/neofs-s3-gw/files/12104855/799.zip)
![799](https://github.com/nspcc-dev/neofs-s3-gw/assets/15652180/4fdb3335-d249-4435-96b7-a6faac225d19)

**Comment by roman-khimov** [comment]
S3 is green here: https://http.fs.neo.org/HXSaMJXk2g8C14ht8HSi7BBaiYZ1HeWh2xnWPGQCg4H6/521-1692114704/index.html#suites/cbd00784275866c60aa75f3c0d6ab31f/38964831eebbd03e/
