### ISSUE TITLE
Cannot upload part S3

### ISSUE THREAD

**Issue by vvarg229** [nspcc-dev/neofs-s3-gw#800]
Tests `test_s3_api_multipart, test_s3_object_multipart` and `test_s3_abort_multipart` failed on step "Upload first part":
`botocore.exceptions.ConnectionClosedError: Connection was closed before we received a valid response from endpoint URL: "https://s3.neofs.devenv:8080/7b78f47e-2ead-4846-8f3e-08478b3b143b/414c459a-9b6e-41b2-ad39-17965bb4889e?uploadId=2c11212e-94ca-498c-806d-e9bd445629e6&partNumber=1".`
and
`botocore.exceptions.ReadTimeoutError: Read timeout on endpoint URL: "https://s3.neofs.devenv:8080/a0c4fb34-214b-4bfd-bf6e-6af1890aceac/14131fe4-d66b-43ab-b607-f7d32c1f2a8b?uploadId=820be485-e9bf-4562-a32d-781b21593904&partNumber=1"`

It's look like a part of https://github.com/nspcc-dev/neofs-s3-gw/issues/799 and https://github.com/nspcc-dev/neofs-node/issues/2440

See result and logs:
https://http.t5.fs.neo.org/86C4P6uJC7gb5n3KkwEGpXRfdczubXyRNW5N9KeJRW73/204-1689413727/index.html#suites/31f34d2653dd4bdfd55e43b57820f6a1/c8de1eb2a109f332/

Environment:
neo-go version 0.101.1
neofs-s3-authmate version v0.27.1
neofs-s3-gw version v0.27.1
neofs-adm version fc824ee9
neofs-ir version c824ee9
neofs-lens version fc824ee9
neofs-cli version fc824ee9
aws-cli/2.13.0
Python/3.11.4
Linux/5.15.0-1041-azure exe/x86_64.ubuntu.22 prompt/off

**Comment by smallhive** [comment]
In #799 tried all _test_s3_gate_. All tests are green. Check allure report, screen inside #799

**Comment by roman-khimov** [comment]
Not a gateway problem, nspcc-dev/neofs-testcases#591.
