### ISSUE TITLE
Add an option to slice objects in the gateway itself

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-s3-gw#808]
Traditionally we use NeoFS API as is and object slicing is performed on the SN end (with appropriate session tokens created and used). We can try slicing in the gateway itself now and see if it works any better or solves any problems. It should be an experimental option for now.

**Comment by carpawell** [comment]
Just to mention my thoughts somewhere: gateways have always been just protocol converters to me. With that option, more apps are responsible for object handling and more apps may make some mistakes `neofs-node` would never be able to fix (or event debug, cause its meta, engine, etc parts has just got the parts/hashes/IDs as is). There would be no "neofs core" with that options accepted: every app would start to be responsible for neofs internals.

So only a noticable perf upgrade can make me think it is a good decision.
