### ISSUE TITLE
make image is broken

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-s3-gw#814]
```
Step 7/13 : RUN make
 ---> Running in 7b7559bcde4f
tree service revision feaa9eace7098c343598bf08fb50746a1e8d2deb
./syncTree.sh: line 9: jq: command not found
```
Caused by cad239ee25523aef17e8577a9687c6dc36f34b49.

**Comment by smallhive** [comment]
Hm, what pipeline is it? I've checked that `jq` exists in both Ubuntu Github runners:
* https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2004-Readme.md
* https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md

**Comment by roman-khimov** [comment]
Doesn't matter, it's running inside a Docker container with alpine on `make image`. Try it on a clean checkout, should reproduce for you as well (you obviously have this tree locally now, so it "works").
