### ISSUE TITLE
Do not add eACL rules related to SYSTEM group

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-s3-gw#817]
* recently https://github.com/nspcc-dev/neofs-sdk-go/releases/tag/v1.0.0-rc.11 was done
* in particular, https://github.com/nspcc-dev/neofs-sdk-go/pull/515 change was introduced.

S3 gateway adds SYSTEM-targeted records to the eACLs:
https://github.com/nspcc-dev/neofs-s3-gw/blob/d6fba1d2e9b31ae29e9e4ff6375b78669418731f/api/handler/acl.go#L157-L165

now it became useless, so this behavior should be fixed/reconsidered

**Comment by roman-khimov** [comment]
https://http.fs.neo.org/HXSaMJXk2g8C14ht8HSi7BBaiYZ1HeWh2xnWPGQCg4H6/736-1694595216/index.html#suites/6655ae0905b32751b8e649efa2b53a9f/452edeee6d54d807/
