### ISSUE TITLE
Not quite accurate hash algorithm for ETags for plaintext objects

### ISSUE THREAD

**Issue by evgeniiz321** [nspcc-dev/neofs-s3-gw#845]
Due to api docs (https://docs.aws.amazon.com/AmazonS3/latest/API/API_Object.html)

```
Objects created by the PUT Object, POST Object, or Copy operation, or through the AWS Management Console, and are encrypted by SSE-S3 or plaintext, have ETags that are an MD5 digest of their object data.
```

So, if we create an object with a body equal to 'bar', we expect it to have the MD5 hash - '37b51d194a7513e45b56f6524f2d51f2'

Currently, looks like some other algorithm is used. And probably that's ok. I'm not sure if this is really something that should be corrected from the s3 side. If we don't fix it on the s3 gate side - i will update the test (test_object_write_check_etag) accordingly.

**Comment by roman-khimov** [comment]
IIRC that's just SHA256, @smallhive?

**Comment by smallhive** [comment]
[Seems](https://github.com/nspcc-dev/neofs-s3-gw/blob/b457e6bd1416d099db0cb189f2f2a176e3527215/api/layer/object.go#L410) like you are right

**Comment by roman-khimov** [comment]
And IIRC the spec allows ETag to be anything, not just MD5 (please check though). In which case it's NOBUG, the test needs to be fixed (or disabled, HTTP meaning of ETags is very permissive).

**Comment by evgeniiz321** [comment]
Spec is rather vague actually:

> ETag
> The entity tag is a hash of the object. The ETag reflects changes only to the contents of an object, not its metadata. The ETag may or may not be an MD5 digest of the object data. Whether or not it is depends on how the object was created and how it is encrypted as described below:
> 
> - Objects created by the PUT Object, POST Object, or Copy operation, or through the AWS Management Console, and are encrypted by SSE-S3 or plaintext, have ETags that are an MD5 digest of their object data.

As for me, it means that for the case with a plaintext as an object data - it should be MD5. But I'm not actually sure that anyone somehow relies here on the hash algorithm.

**Comment by roman-khimov** [comment]
Let's just document the behavior we have for now. There is an etag, it's correct as per HTTP definition of it, it doesn't immediately conflict with S3 spec, so until it's a real problem for anyone we can have it as is.
