### ISSUE TITLE
PutObject: handle metadata with an empty string as a value more gracefully

### ISSUE THREAD

**Issue by evgeniiz321** [nspcc-dev/neofs-s3-gw#846]
If we put an object with metadata value equal to empty string "", we got 500 from the s3 gate:

```
2023-10-12T00:44:17.218Z	error	handler/util.go:29	call method	{"status": 500, "request_id": "3bb78287-09cd-4b0d-901b-fe341066115c", "method": "PutObject", "bucket": "yournamehere-xxaxwdqfj5jh3mk8-1", "object": "foo", "description": "could not upload object", "error": "save object via connection pool: init writing on API client: client failure: status: code = 1024 message = empty attribute value", "body close errors": []}
```

Corresponding code: 
```
metadata_dict = {"meta1": ""}
client.put_object(Bucket=bucket_name, Key="foo", Body="bar", Metadata=metadata_dict)
```

Expected behavior is to create an object and then return this empty string "" upon get requests inside Metadata.

**Comment by roman-khimov** [comment]
Not sure this one could be fixed. @smallhive, @cthulhu-rider?

**Comment by smallhive** [comment]
It looks like this part _empty attribute value_ is returned from the node, and we can't handle this inside gate. On the other hand, saving an empty attribute value looks suspicious. What is the case?

We may drop such attribute on the gate side, to handle this error

**Comment by roman-khimov** [comment]
Dropping this attribute is not an option, it should be present, presence with zero value and missing attribute are different things (refs. nspcc-dev/neofs-api#256). But we can have this explicitly unsupported for now (returning "unsupported" error from the GW immediately), it's a very specific use case. Let's do this, document it and then get back to it if it's really needed for any reason.
