### ISSUE TITLE
Convert to new testcases

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-s3-gw#934]
## Is your feature request related to a problem? Please describe.
I'm always frustrated when I see old test jobs here, we do run a subset of testcases for S3 gateway, but it's still dev-env based.

## Describe the solution you'd like
Port https://github.com/nspcc-dev/neofs-node/pull/2765 here.

## Describe alternatives you've considered
No alternatives, the only way is forward.

**Comment by evgeniiz321** [comment]
closed by https://github.com/nspcc-dev/neofs-s3-gw/pull/945
