### ISSUE TITLE
S3 tests fail heavy after last NeoFS SDK upgrade

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-s3-gw#947]
* after #943

S3 tests finished with [report](https://rest.fs.neo.org/7ZVSQHtioVRiDT2btN9xEmQhczXV9vryCEAHUawfD8Sc/222-1712914796/index.html) (can expire)

2-month SDK diff brought a lot of changes. Most of the tests fail with the `Access denied` hinting at a relationship with tokens - most likely bearer

while test failure is bad overall, i expect them to work with neofs-node@v0.41.0 ([unreleased](https://github.com/nspcc-dev/neofs-node/milestone/58) for now). We could either w8 4 the release and test with it or try to dive into the problem right now. Manual reproduction at the moment can be quite non-trivial though, me personally havent got such experience yet

btw system tests feel not so [bad](https://rest.fs.neo.org/7ZVSQHtioVRiDT2btN9xEmQhczXV9vryCEAHUawfD8Sc/214-1712915369/index.html#)

**Comment by roman-khimov** [comment]
Waiting for 0.41.0 NeoFS.

**Comment by roman-khimov** [comment]
Irrelevant now, works fine.
