### ISSUE TITLE
Potentially insecure hkdf use

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-s3-gw#951]
## Current Behavior
`kdf := hkdf.New(hash, secret, nil, nil)`. No salt, no app-specific info.

## Expected Behavior
App-specific info and salt used.

## Possible Solution
Hardcode info, add some salt. Breaking change, but the gateway is not used in production.

## Your Environment
* Version of the product used: 0.30.0

**Comment by roman-khimov** [comment]
Salt is to be stored somewhere nearby, as usual.

**Comment by cthulhu-rider** [comment]
> Salt is to be stored somewhere

what do u mean - in what storage?
