### ISSUE TITLE
GET of a multipart object fails

### ISSUE THREAD

**Issue by evgeniiz321** [nspcc-dev/neofs-s3-gw#954]
s3tests_boto3.functional.test_s3#test_multipart_upload_overwrite_existing_object
s3tests_boto3.functional.test_s3_neofs#test_multipart_upload

Upload multipart object
Try to get it -> get an error on reading from the response stream, e.g:

```
botocore.exceptions.ResponseStreamingError: An error occurred while reading from response stream: ('Connection broken: IncompleteRead(409 bytes read, 10485351 more expected)', IncompleteRead(409 bytes read, 10485351 more expected))
```

https://rest.fs.neo.org/7ZVSQHtioVRiDT2btN9xEmQhczXV9vryCEAHUawfD8Sc/239-1715825418/index.html#suites/6d7c9ec7c4f3e4460ae14fd266a64e04/e9c65890413d3e9a/

**Comment by smallhive** [comment]
These tests are going to be fixed by https://github.com/nspcc-dev/neofs-s3-gw/pull/957
