### ISSUE TITLE
After a parallel deletion of versioned objects, list objects returns info about them

### ISSUE THREAD

**Issue by evgeniiz321** [nspcc-dev/neofs-s3-gw#955]
s3tests_boto3.functional.test_s3#test_multipart_upload_overwrite_existing_object

Create versioned objects
Issue parallel deletion commands to the same objects
Issue list objects
Expect to see an empty list, but got an info about deleted objects

https://rest.fs.neo.org/7ZVSQHtioVRiDT2btN9xEmQhczXV9vryCEAHUawfD8Sc/239-1715825418/index.html#suites/6d7c9ec7c4f3e4460ae14fd266a64e04/c644040f4856b216/

**Comment by roman-khimov** [comment]
Yellow: https://rest.fs.neo.org/7ZVSQHtioVRiDT2btN9xEmQhczXV9vryCEAHUawfD8Sc/275-1718625554/index.html#suites/6d7c9ec7c4f3e4460ae14fd266a64e04/c6a3fde227ced641/

**Comment by roman-khimov** [comment]
https://rest.fs.neo.org/7ZVSQHtioVRiDT2btN9xEmQhczXV9vryCEAHUawfD8Sc/275-1718625554/index.html#suites/6d7c9ec7c4f3e4460ae14fd266a64e04/f375e4db6ab28d9f/

Which one is problematic here? Description says `test_multipart_upload_overwrite_existing_object`, but the link is to `test_versioning_concurrent_multi_object_delete`.

**Comment by roman-khimov** [comment]
Blocked by https://github.com/nspcc-dev/s3-tests/issues/69
