### ISSUE TITLE
No match for platform in manifest for darwin system

### ISSUE THREAD

**Issue by mike-petrov** [nspcc-dev/neofs-s3-gw#959]
I get an error when I try to run it on darwin system:

`ERROR: failed to solve: nspccdev/neofs-s3-gw:0.30.0: no match for platform in manifest: not found`

**Comment by smallhive** [comment]
It seems the issue will be fixed with the next release, because of [this](https://github.com/nspcc-dev/neofs-s3-gw/commit/58fcb88ff01c67893862ea0e9bd2f83e3b75cc86)

**Comment by roman-khimov** [comment]
Yeah, it just needs a release. Meanwhile you can build an old one locally.
