### ISSUE TITLE
Update compatibility table and test results

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-s3-gw#984]
## Is your feature request related to a problem? Please describe.
I'm always frustrated when our documentation is lagging behind. We've got these documents:
https://github.com/nspcc-dev/neofs-s3-gw/blob/master/docs/aws_s3_compat.md
https://github.com/nspcc-dev/neofs-s3-gw/blob/master/docs/s3_test_results.md

And we're certainly better now than we were at the time of their last update.

## Describe the solution you'd like
Update test results, update compatibility table based on these test results.

**Comment by smallhive** [comment]
I've checked commits for one year. I found just a small #998 missing in unsupported methods. It seems another valuable change has been already added to the docs. Maybe I missed something, but nothing stuck to my eye

**Comment by roman-khimov** [comment]
OK, let's keep it open till @evgeniiz321 returns.
